<?php require './templates/header.phtml' ?>

<ul class="list-group list-group-item-info">
<?php foreach($categorias as $categoria): ?>
    <li class="list-group-item list-group-item-action list-group-item-info">
        <div>
            <b><?= $categoria->id ?></b> | <?=$categoria->nombre?>
            <button><a href="formCategorias/<?=$categoria->id?>">Editar</a></button>
            <button><a href="categorias/<?=$categoria->id?>">Ver</a></button>
        </div>
        
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> categorias</small></p>


<?php require './templates/footer.phtml' ?>