<?php require './templates/header.phtml' ?>

<ul class="list-group list-group-item-info">
    <li class="list-group-item list-group-item-action list-group-item-info">
        <div>
            <b><?= $categoria->id ?></b> | <?=substr($categoria->nombre,0,25)?>
            <button><a href="formCategorias/<?=$categoria->id?>">Editar</a></button>
            <button><a href="categorias">volver</a></button>
            <button><a href="deleteCategoria/<?=$categoria->id?>">Borrar</a></button>
        </div>
        
    </li>
</ul>



<?php require './templates/footer.phtml' ?>