<?php require './templates/header.phtml' ?>

<div class="d-flex justify-content-around mb-3">
<?php 

    foreach ($categorias as $cate) {
        ?>
            <button><a href="products?filtro=<?=$cate->id?>"> <?=$cate->nombre?> </a></button>
        <?php
    }

?>

</div>

<ul class="list-group list-group-item-info">
    <?php foreach ($products as $product) : ?>
        <li class="list-group-item list-group-item-action list-group-item-info d-flex justify-content-center">
            <div>
                <b> <?= $product->categoria ?> | <?= substr($product->nombre, 0, 25) ?></b>
                <button><a href="formProducts/<?= $product->id ?>">Editar</a></button>
                <button><a href="products/<?= $product->id ?>">Ver</a></button>
            </div>

        </li>
    <?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> Productos</small></p>


<?php require './templates/footer.phtml' ?>